<?php

namespace Database\Seeders;

use App\Models\Portfolio;
use App\Models\PortfolioGallery;
use Illuminate\Database\Seeder;

class PortfolioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $portfolios = [
            [
                'title' => 'Stellar Tech Solutions',
                'client' => 'Cameron Williamson',
                'industry' => 'Technology',
                'overview' => 'Stellar Tech Solutions is a leading provider of innovative technology services designed to empower businesses in today\'s fast-paced digital landscape. We specialize in crafting customized IT solutions, integrating cutting-edge technologies, and delivering robust cybersecurity strategies to ensure your organization\'s growth, efficiency, and security.',
                'about_project' => 'Our team of experienced professionals is dedicated to understanding your unique challenges and goals, offering tailored services that align with your vision. From seamless system integration and managed IT services to advanced cloud solutions and proactive cybersecurity measures, we help businesses streamline operations, enhance productivity, and safeguard critical data.',
                'image' => 'uploads/portfolios/01K2Z3DEAK6RVSHC9R3VS5HXQJ.png',
                'slug' => 'stellar-tech-solutions',
                'short_description' => 'We redesigned Stellar Tech\'s website to enhance their digital presence and improve user experience.',
                'testimonial' => 'The team at Vienhance Studio delivered an exceptional website that perfectly captures our brand identity and exceeds our expectations. The attention to detail and user experience is outstanding.',
                'meta_title' => 'Stellar Tech Solutions - Web Design Project | Vienhance Studio',
                'meta_description' => 'See how we redesigned Stellar Tech Solutions\' website to enhance their digital presence and improve user experience.',
                'meta_keywords' => 'web design, branding, tech company, responsive design, user experience',
                'og_title' => 'Stellar Tech Solutions - Web Design Project',
                'og_description' => 'See how we redesigned Stellar Tech Solutions\' website to enhance their digital presence and improve user experience.',
                'og_image' => null,
                'og_type' => 'website',
                'og_url' => 'https://vienhancestudio.com/portfolio/stellar-tech-solutions',
                'og_site_name' => 'Vienhance Studio',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Stellar Tech Solutions - Web Design Project',
                'twitter_description' => 'See how we redesigned Stellar Tech Solutions\' website to enhance their digital presence and improve user experience.',
                'twitter_image' => null,
                'twitter_site' => '@vienhancestudio',
                'twitter_creator' => '@vienhancestudio',
                'canonical_url' => 'https://vienhancestudio.com/portfolio/stellar-tech-solutions',
                'schema_markup' => '{"url":"https://vienhancestudio.com/portfolio/stellar-tech-solutions","name":"Stellar Tech Solutions Website","@type":"CreativeWork","creator":{"name":"Vienhance Studio","@type":"Organization"},"@context":"https://schema.org","dateCreated":"2023-01-25","description":"Professional web design and development for Stellar Tech Solutions"}',
                'priority' => 0.80,
                'change_frequency' => 'monthly',
                'status' => 'live',
                'gallery' => [
                    ['image' => 'uploads/portfolio-gallery/01K2Z46VVHTK9456QAKDC0JBQ1.png', 'alt_text' => 'Stellar Tech Solutions Homepage', 'caption' => 'Homepage Design', 'sort_order' => 1],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Stellar Tech Solutions Dashboard', 'caption' => 'Dashboard Interface', 'sort_order' => 2],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Stellar Tech Solutions Mobile', 'caption' => 'Mobile Responsive Design', 'sort_order' => 3],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Stellar Tech Solutions Admin', 'caption' => 'Admin Panel', 'sort_order' => 4],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Stellar Tech Solutions Analytics', 'caption' => 'Analytics Dashboard', 'sort_order' => 5],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Stellar Tech Solutions Features', 'caption' => 'Key Features', 'sort_order' => 6],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Stellar Tech Solutions Integration', 'caption' => 'System Integration', 'sort_order' => 7],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Stellar Tech Solutions Final', 'caption' => 'Final Implementation', 'sort_order' => 8],
                ],
            ],
            [
                'title' => 'Green Wave Foods',
                'client' => 'Sarah Johnson',
                'industry' => 'Food & Beverage',
                'overview' => 'Green Wave Foods needed a modern, user-friendly e-commerce platform that could handle their growing customer base while maintaining the organic, sustainable brand image they\'ve built.',
                'about_project' => 'Creating an intuitive shopping experience that reflects the company\'s commitment to sustainability while ensuring fast loading times and mobile responsiveness. The platform needed to showcase their organic products effectively while providing a seamless checkout process.',
                'image' => 'work-image-2.jpg',
                'slug' => 'green-wave-foods',
                'short_description' => 'We built a user-friendly Shopping platform for Green Wave Foods.',
                'testimonial' => 'The e-commerce platform Vienhance Studio created for us has significantly increased our online sales. The user experience is intuitive and the mobile responsiveness is perfect.',
                'meta_title' => 'Green Wave Foods - E-commerce Platform | Vienhance Studio',
                'meta_description' => 'Modern e-commerce platform for Green Wave Foods with mobile-first design and sustainable branding.',
                'meta_keywords' => 'e-commerce, food platform, mobile design, sustainable branding, online shopping',
                'og_title' => 'Green Wave Foods - E-commerce Platform',
                'og_description' => 'Modern e-commerce platform for Green Wave Foods with mobile-first design and sustainable branding.',
                'og_image' => 'work-image-2.jpg',
                'og_type' => 'website',
                'og_url' => 'https://vienhancestudio.com/portfolio/green-wave-foods',
                'og_site_name' => 'Vienhance Studio',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Green Wave Foods - E-commerce Platform',
                'twitter_description' => 'Modern e-commerce platform for Green Wave Foods with mobile-first design and sustainable branding.',
                'twitter_image' => 'work-image-2.jpg',
                'twitter_site' => '@vienhancestudio',
                'twitter_creator' => '@vienhancestudio',
                'canonical_url' => 'https://vienhancestudio.com/portfolio/green-wave-foods',
                'schema_markup' => '{"url":"https://vienhancestudio.com/portfolio/green-wave-foods","name":"Green Wave Foods E-commerce Platform","@type":"CreativeWork","creator":{"name":"Vienhance Studio","@type":"Organization"},"@context":"https://schema.org","dateCreated":"2023-03-15","description":"Modern e-commerce platform for organic food products"}',
                'priority' => 0.80,
                'change_frequency' => 'monthly',
                'status' => 'live',
                'gallery' => [
                    ['image' => 'post-4.jpg', 'alt_text' => 'Green Wave Foods Homepage', 'caption' => 'Homepage Design', 'sort_order' => 1],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Green Wave Foods Products', 'caption' => 'Product Catalog', 'sort_order' => 2],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Green Wave Foods Cart', 'caption' => 'Shopping Cart', 'sort_order' => 3],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Green Wave Foods Checkout', 'caption' => 'Checkout Process', 'sort_order' => 4],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Green Wave Foods Mobile', 'caption' => 'Mobile Experience', 'sort_order' => 5],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Green Wave Foods Admin', 'caption' => 'Admin Dashboard', 'sort_order' => 6],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Green Wave Foods Analytics', 'caption' => 'Sales Analytics', 'sort_order' => 7],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Green Wave Foods Final', 'caption' => 'Final Platform', 'sort_order' => 8],
                ],
            ],
            [
                'title' => 'Horizon Real Estate',
                'client' => 'Michael Chen',
                'industry' => 'Real Estate',
                'overview' => 'Horizon Real Estate required a complete brand identity overhaul to establish themselves as a trusted name in the competitive real estate market.',
                'about_project' => 'Developing a brand identity that conveys trust, professionalism, and local expertise while standing out in a crowded market. The project included logo design, brand guidelines, and marketing materials.',
                'image' => 'work-image-3.jpg',
                'slug' => 'horizon-real-estate',
                'short_description' => 'We helped Horizon Real Estate establish a trusted brand identity.',
                'testimonial' => 'Vienhance Studio transformed our brand identity completely. The new logo and design system perfectly represents our values and has helped us stand out in the competitive real estate market.',
                'meta_title' => 'Horizon Real Estate - Brand Identity Design | Vienhance Studio',
                'meta_description' => 'Complete brand identity overhaul for Horizon Real Estate including logo design and marketing materials.',
                'meta_keywords' => 'brand identity, logo design, real estate, marketing materials, brand guidelines',
                'og_title' => 'Horizon Real Estate - Brand Identity Design',
                'og_description' => 'Complete brand identity overhaul for Horizon Real Estate including logo design and marketing materials.',
                'og_image' => 'work-image-3.jpg',
                'og_type' => 'website',
                'og_url' => 'https://vienhancestudio.com/portfolio/horizon-real-estate',
                'og_site_name' => 'Vienhance Studio',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Horizon Real Estate - Brand Identity Design',
                'twitter_description' => 'Complete brand identity overhaul for Horizon Real Estate including logo design and marketing materials.',
                'twitter_image' => 'work-image-3.jpg',
                'twitter_site' => '@vienhancestudio',
                'twitter_creator' => '@vienhancestudio',
                'canonical_url' => 'https://vienhancestudio.com/portfolio/horizon-real-estate',
                'schema_markup' => '{"url":"https://vienhancestudio.com/portfolio/horizon-real-estate","name":"Horizon Real Estate Brand Identity","@type":"CreativeWork","creator":{"name":"Vienhance Studio","@type":"Organization"},"@context":"https://schema.org","dateCreated":"2023-02-10","description":"Complete brand identity design for real estate company"}',
                'priority' => 0.80,
                'change_frequency' => 'monthly',
                'status' => 'live',
                'gallery' => [
                    ['image' => 'post-4.jpg', 'alt_text' => 'Horizon Real Estate Logo', 'caption' => 'Logo Design', 'sort_order' => 1],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Horizon Real Estate Brand', 'caption' => 'Brand Guidelines', 'sort_order' => 2],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Horizon Real Estate Business Cards', 'caption' => 'Business Cards', 'sort_order' => 3],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Horizon Real Estate Brochures', 'caption' => 'Marketing Brochures', 'sort_order' => 4],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Horizon Real Estate Website', 'caption' => 'Website Design', 'sort_order' => 5],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Horizon Real Estate Social Media', 'caption' => 'Social Media Assets', 'sort_order' => 6],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Horizon Real Estate Signage', 'caption' => 'Office Signage', 'sort_order' => 7],
                    ['image' => 'post-4.jpg', 'alt_text' => 'Horizon Real Estate Final', 'caption' => 'Final Brand Package', 'sort_order' => 8],
                ],
            ],
            [
                'title' => 'Hylnfluencer',
                'client' => 'Hylnfluencer',
                'industry' => 'Marketing',
                'overview' => 'Hylnfluencer, is redefining affiliate marketing with a brand-first philosophy. Their primary goal is to empower affiliates for unparalleled success. Through innovation, cutting-edge technologies, and revolutionary commission structures, Hylnfluncer lead the industry.',
                'about_project' => ' Transparent, lasting partnerships and high-converting traffic drive exceptional value for their clients. Maximized affiliate earnings, a dynamic global community, and unwavering brand integrity set us apart as the go-to platform, shaping the future of affiliate marketing.',
                'image' => 'uploads/portfolios/01K2Z4PRAYG8HFHPH1XMAR7WA0.png',
                'slug' => 'hylnfluencer',
                'short_description' => 'Hylnfluencer, is redefining affiliate marketing with a brand-first philosophy. ',
                'testimonial' => null,
                'meta_title' => null,
                'meta_description' => null,
                'meta_keywords' => null,
                'og_title' => null,
                'og_description' => null,
                'og_image' => null,
                'og_type' => null,
                'og_url' => null,
                'og_site_name' => null,
                'twitter_card' => null,
                'twitter_title' => null,
                'twitter_description' => null,
                'twitter_image' => null,
                'twitter_site' => null,
                'twitter_creator' => null,
                'canonical_url' => null,
                'schema_markup' => null,
                'priority' => null,
                'change_frequency' => null,
                'status' => 'live',
                'gallery' => [
                    ['image' => 'uploads/portfolio-gallery/01K2Z4SDK50H1JAWY140MKEZR4.png', 'alt_text' => 'Hylnfluencer', 'caption' => null, 'sort_order' => 0],
                    ['image' => 'uploads/portfolio-gallery/01K2Z4STY9FBBKBXY1PAPPE5PE.png', 'alt_text' => 'Hylnfluencer', 'caption' => null, 'sort_order' => 1],
                    ['image' => 'uploads/portfolio-gallery/01K2Z4T78Y8G9DEX20456DWN7Z.png', 'alt_text' => 'Hylnfluencer', 'caption' => null, 'sort_order' => 3],
                    ['image' => 'uploads/portfolio-gallery/01K2Z4TJF93SPJ14QTPME23G22.png', 'alt_text' => 'Hylnfluencer', 'caption' => null, 'sort_order' => 4],
                    ['image' => 'uploads/portfolio-gallery/01K2Z4TY67Z32JQADQA1HMAWD1.png', 'alt_text' => 'Hylnfluencer', 'caption' => null, 'sort_order' => 5],
                    ['image' => 'uploads/portfolio-gallery/01K2Z4VBR9BGW28D6ZWYG3D4JY.png', 'alt_text' => 'Hylnfluencer', 'caption' => null, 'sort_order' => 6],
                ],
            ],
            [
                'title' => 'EV Charging Station App Design',
                'client' => 'EV Charging Station App Design',
                'industry' => 'Technology',
                'overview' => 'EV Charging Station App Design',
                'about_project' => '       .',
                'image' => 'uploads/portfolios/01K2Z59KZWYCJ58A9WS03634K2.png',
                'slug' => 'ev-charging-station-app-design',
                'short_description' => 'EV Charging Station App Design',
                'testimonial' => null,
                'meta_title' => null,
                'meta_description' => null,
                'meta_keywords' => null,
                'og_title' => null,
                'og_description' => null,
                'og_image' => null,
                'og_type' => null,
                'og_url' => null,
                'og_site_name' => null,
                'twitter_card' => null,
                'twitter_title' => null,
                'twitter_description' => null,
                'twitter_image' => null,
                'twitter_site' => null,
                'twitter_creator' => null,
                'canonical_url' => null,
                'schema_markup' => null,
                'priority' => null,
                'change_frequency' => null,
                'status' => 'live',
                'gallery' => [
                    ['image' => 'uploads/portfolio-gallery/01K2Z5AS8T5RGDS88E2AZT2FCE.png', 'alt_text' => 'EV Charging Station App Design', 'caption' => 'EV Charging Station App Design', 'sort_order' => 0],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5B7FD7FCRKC5ETPDD94TV.png', 'alt_text' => 'EV Charging Station App Design', 'caption' => 'EV Charging Station App Design', 'sort_order' => 2],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5BHXPQTP36GDRH6N78PX6.png', 'alt_text' => 'EV Charging Station App Design', 'caption' => 'EV Charging Station App Design', 'sort_order' => 3],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5C2QQ9WFE0KGKQAPGMXFF.png', 'alt_text' => 'EV Charging Station App Design', 'caption' => 'EV Charging Station App Design', 'sort_order' => 4],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5CG6A9ACAX8JFRJS9B50C.png', 'alt_text' => 'EV Charging Station App Design', 'caption' => 'EV Charging Station App Design', 'sort_order' => 1],
                ],
            ],
            [
                'title' => 'SI Industries Branding ',
                'client' => 'SI Industries Branding ',
                'industry' => 'Manufacturing',
                'overview' => 'SI Industries Branding ',
                'about_project' => 'SI Industries Branding of a Plywood manufacturing Company ',
                'image' => 'uploads/portfolios/01K2Z5Q38NZPGSYHDG82K27J7Z.jpg',
                'slug' => 'si-industries-branding ',
                'short_description' => 'SI Industries Branding of a Plywood manufacturing Company ',
                'testimonial' => null,
                'meta_title' => null,
                'meta_description' => null,
                'meta_keywords' => null,
                'og_title' => null,
                'og_description' => null,
                'og_image' => null,
                'og_type' => null,
                'og_url' => null,
                'og_site_name' => null,
                'twitter_card' => null,
                'twitter_title' => null,
                'twitter_description' => null,
                'twitter_image' => null,
                'twitter_site' => null,
                'twitter_creator' => null,
                'canonical_url' => null,
                'schema_markup' => null,
                'priority' => null,
                'change_frequency' => null,
                'status' => 'live',
                'gallery' => [
                    ['image' => 'uploads/portfolio-gallery/01K2Z5R43QHH2FH5YH48T60JSR.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 0],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5RFJKQ57C3JVWYZJK683Z.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 1],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5RRTY6GZADJNV6CAC7889.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 2],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5S2JT2VKGQRS9YQFV9XKM.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 3],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5SCK3T9JDTWD80BMFV3XM.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 4],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5TB5179EWDF8TX6SGMRYY.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 5],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5TN0D9EP73A22QAR59HD3.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 6],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5V3SW3MDF145JBB23EY3A.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 7],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5VFEZ42PS4W3KFGH2S1WC.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 8],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5VSRHSPQCMR1BA05QA077.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 9],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5W6N1BABZHMFSCBHM2M40.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 10],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5WHQ7JZK707PMFRAZ1A03.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 11],
                    ['image' => 'uploads/portfolio-gallery/01K2Z5WXDH93F2RWPA4W4CY8QJ.jpg', 'alt_text' => 'SI Industries', 'caption' => 'SI Industries', 'sort_order' => 12],
                ],
            ],
            [
                'title' => 'Ramdhan jewellers',
                'client' => 'Ramdhan jewellers',
                'industry' => 'Jewellers',
                'overview' => 'Ramdhan jewellers',
                'about_project' => 'Ramdhan jewellers',
                'image' => 'uploads/portfolios/01K2Z69JRXSGR6YHEC96W7C5WK.png',
                'slug' => 'ramdhan-jewellers',
                'short_description' => 'Ramdhan jewellers',
                'testimonial' => null,
                'meta_title' => null,
                'meta_description' => null,
                'meta_keywords' => null,
                'og_title' => null,
                'og_description' => null,
                'og_image' => null,
                'og_type' => null,
                'og_url' => null,
                'og_site_name' => null,
                'twitter_card' => null,
                'twitter_title' => null,
                'twitter_description' => null,
                'twitter_image' => null,
                'twitter_site' => null,
                'twitter_creator' => null,
                'canonical_url' => null,
                'schema_markup' => null,
                'priority' => null,
                'change_frequency' => null,
                'status' => 'live',
                'gallery' => [
                    ['image' => 'uploads/portfolio-gallery/01K2Z6A5GS0Y2CGJ1XPAHTV0B3.png', 'alt_text' => 'Ramdhan jewellers', 'caption' => 'Ramdhan jewellers', 'sort_order' => 0],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6AGP2QTRKQBKW191J58A3.png', 'alt_text' => 'Ramdhan jewellers', 'caption' => 'Ramdhan jewellers', 'sort_order' => 1],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6AW5BD60T1HGTCYD0RRSK.png', 'alt_text' => 'Ramdhan jewellers', 'caption' => 'Ramdhan jewellers', 'sort_order' => 2],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6B6H8MTKY8B6D1VFEMM9F.png', 'alt_text' => 'Ramdhan jewellers', 'caption' => 'Ramdhan jewellers', 'sort_order' => 3],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6BHV1371XG6W8M1YRQ6N8.png', 'alt_text' => 'Ramdhan jewellers', 'caption' => 'Ramdhan jewellers', 'sort_order' => 4],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6BXB7C8H1SY1WXKTNHJ6V.png', 'alt_text' => 'Ramdhan jewellers', 'caption' => 'Ramdhan jewellers', 'sort_order' => 5],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6C7JC5Q0XY6F5S34P4EW1.png', 'alt_text' => 'Ramdhan jewellers', 'caption' => 'Ramdhan jewellers', 'sort_order' => 6],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6CH4D7D75VWM9DTS8KB8Q.png', 'alt_text' => 'Ramdhan jewellers', 'caption' => 'Ramdhan jewellers', 'sort_order' => 7],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6CVA6NK9NRBBQZMFSZ3PV.png', 'alt_text' => 'Ramdhan jewellers', 'caption' => 'Ramdhan jewellers', 'sort_order' => 8],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6D6C14A8KMPT7HNP5N0EG.png', 'alt_text' => 'Ramdhan jewellers', 'caption' => 'Ramdhan jewellers', 'sort_order' => 9],
                ],
            ],
            [
                'title' => 'Layali Arts',
                'client' => 'Layali Arts',
                'industry' => 'Manufacturer',
                'overview' => 'Layali Arts',
                'about_project' => 'Layali Arts',
                'image' => 'uploads/portfolios/01K2Z6J8HKZW3E0NA1NDVTC74Q.jpg',
                'slug' => 'layali-arts',
                'short_description' => 'Layali Arts',
                'testimonial' => null,
                'meta_title' => null,
                'meta_description' => null,
                'meta_keywords' => null,
                'og_title' => null,
                'og_description' => null,
                'og_image' => null,
                'og_type' => null,
                'og_url' => null,
                'og_site_name' => null,
                'twitter_card' => null,
                'twitter_title' => null,
                'twitter_description' => null,
                'twitter_image' => null,
                'twitter_site' => null,
                'twitter_creator' => null,
                'canonical_url' => null,
                'schema_markup' => null,
                'priority' => null,
                'change_frequency' => null,
                'status' => 'live',
                'gallery' => [
                    ['image' => 'uploads/portfolio-gallery/01K2Z6JRDRJRWHSPTTS31QMM4C.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 0],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6K26Q5CRDE0TBPBP7SAF7.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 1],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6KC5S542RX8EW14Z3S6JY.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 2],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6KP2FJGGENCZC8WCHG6XG.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 3],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6M1MYSSVY163V2T39ED0K.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 4],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6N0RTKZDH8KGMCEQ2R9WR.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 5],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6NB1ZPNW1EFP7JVJASSB7.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 6],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6NNNNW5SYNNCDWXR83HBH.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 7],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6P1C2KNQX0VEV50RA49SA.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 8],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6PWKRMYZR510QVZERBCV7.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 9],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6Q82CBSXDDNY78S7STW0R.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 10],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6QNARHCPBRMGXV57X6XHW.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 12],
                    ['image' => 'uploads/portfolio-gallery/01K2Z6RM5GGK2YX9WX24J3NFW1.jpg', 'alt_text' => 'Layali ', 'caption' => 'Layali ', 'sort_order' => 11],
                ],
            ],
        ];

        foreach ($portfolios as $portfolioData) {
            $galleryData = $portfolioData['gallery'];
            unset($portfolioData['gallery']);

            $portfolio = Portfolio::create($portfolioData);

            foreach ($galleryData as $galleryItem) {
                PortfolioGallery::create([
                    'portfolio_id' => $portfolio->id,
                    'image' => $galleryItem['image'],
                    'alt_text' => $galleryItem['alt_text'],
                    'caption' => $galleryItem['caption'],
                    'sort_order' => $galleryItem['sort_order'],
                ]);
            }
        }
    }
}
